# Generated by Django 5.2.5 on 2026-03-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InterfazSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('template', models.CharField(blank=True, max_length=200, null=True)),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Interfaz del sistema',
                'verbose_name_plural': 'Interfaces del sistema',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('es_administrador_empresa', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PermisoInterfazUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_consultar', models.BooleanField(default=False)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_modificar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('interfaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to='usuarios.interfazsistema')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_interfaz', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Permiso por interfaz',
                'verbose_name_plural': 'Permisos por interfaz',
                'ordering': ['perfil__user__username', 'interfaz__modulo', 'interfaz__nombre'],
                'unique_together': {('perfil', 'interfaz')},
            },
        ),
    ]
