# Generated by Django 5.2.5 on 2025-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'C.C'), ('NIT', 'NIT'), ('CE', 'ID de extranjería')], max_length=5)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_tercero', models.CharField(choices=[('Empleado', 'Empleado'), ('Proveedor', 'Proveedor'), ('Cliente', 'Cliente')], max_length=20)),
            ],
        ),
    ]
