# Generated by Django 5.2.5 on 2025-09-08 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('movimiento', models.BooleanField(default=False)),
                ('centro_costo', models.BooleanField(default=False)),
                ('criterio1', models.CharField(blank=True, max_length=100, null=True)),
                ('criterio2', models.CharField(blank=True, max_length=100, null=True)),
                ('criterio3', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.PositiveIntegerField(default=1, editable=False)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='myapp.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['codigo'],
            },
        ),
    ]
