# Generated by Django 5.2.5 on 2025-09-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_cuenta_contable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Documento contable',
                'verbose_name_plural': 'Documentos contables',
                'ordering': ['codigo'],
            },
        ),
    ]
