# Generated by Django 5.2.5 on 2025-09-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_documentocontable_next_number_asientocontable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('centro_costo', models.BooleanField(default=False)),
                ('criterio1', models.CharField(blank=True, max_length=100, null=True)),
                ('criterio2', models.CharField(blank=True, max_length=100, null=True)),
                ('criterio3', models.CharField(blank=True, max_length=100, null=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='myapp.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.cuentacontable')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.tercero')),
            ],
            options={
                'verbose_name': 'Movimiento contable',
                'verbose_name_plural': 'Movimientos contables',
            },
        ),
    ]
