# Generated by Django 5.2.5 on 2025-09-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_movimientocontable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentocontable',
            options={'ordering': ['codigo']},
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='documentocontable',
            name='padding',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='myapp.documentocontable'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='documentocontable',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        # migrations.AddConstraint(
        #     model_name='asientocontable',
        #     constraint=models.UniqueConstraint(fields=('documento', 'numero'), name='uniq_doc_numero'),
        # ),
    ]
