# Generated by Django 5.2.5 on 2025-09-15 21:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_documentocontable_options_and_more'),  # <-- ajusta el nombre si tu 0006 se llama distinto
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(
                fields=('documento', 'numero'),
                name='uniq_doc_numero',
            ),
        ),
    ]