# Generated by Django 5.2.5 on 2025-09-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_add_unique_doc_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientocontable',
            options={'ordering': ['id'], 'verbose_name': 'Movimiento contable', 'verbose_name_plural': 'Movimientos contables'},
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='criterio1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='criterio2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='criterio3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
