# Generated by Django 5.2.5 on 2025-09-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_movimientocontable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterField(
            model_name='documentocontable',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
