# Generated by Django 5.2.5 on 2026-01-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_asientocontable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('causa_fv', models.BooleanField(default=False)),
                ('causa_inventario', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('cta_cartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_cta_cartera', to='myapp.cuentacontable')),
                ('cta_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_cta_costo', to='myapp.cuentacontable')),
                ('cta_impuestos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_cta_impuestos', to='myapp.cuentacontable')),
                ('cta_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_cta_ingreso', to='myapp.cuentacontable')),
                ('cta_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_cta_inventario', to='myapp.cuentacontable')),
                ('documento_fv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_documento_fv', to='myapp.documentocontable')),
            ],
            options={
                'verbose_name': 'Producto / Servicio',
                'verbose_name_plural': 'Productos / Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
