# Generated by Django 5.2.5 on 2026-01-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_productoservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='doc_fv',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='doc_nc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
