# Generated by Django 5.2.5 on 2026-01-28 21:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_productoservicio_doc_fv_productoservicio_doc_nc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=20, unique=True)),
                ('fecha_factura', models.DateField(default=django.utils.timezone.now)),
                ('dias_pago', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('nit', models.CharField(max_length=20)),
                ('razon_social', models.CharField(blank=True, default='', max_length=200)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('abonos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FacturaVentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='myapp.facturaventa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
