# Generated by Django 5.2.5 on 2026-02-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_facturaventa_facturaventalinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('nit', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('sucursal', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('resolucion_dian', models.CharField(max_length=200)),
                ('resolucion_autoretenedor_dian', models.CharField(max_length=200)),
                ('resolucion_autoretenedor_ica', models.CharField(max_length=200)),
                ('entidades_pago', models.TextField()),
            ],
        ),
    ]
