# Generated by Django 5.2.5 on 2026-02-10 00:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_datosfacturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=20, unique=True)),
                ('fecha_nc', models.DateField()),
                ('nit', models.CharField(blank=True, default='', max_length=50)),
                ('razon_social', models.CharField(blank=True, default='', max_length=200)),
                ('correo', models.CharField(blank=True, default='', max_length=200)),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
                ('motivo', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='myapp.facturaventa')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='myapp.notacredito')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
