# Generated by Django 5.2.5 on 2026-02-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_notacredito_notacreditolinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('entidad_bancaria', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=60, null=True)),
                ('cuenta_contable', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medio_pago',
                'ordering': ['id'],
            },
        ),
    ]
