# Generated by Django 5.2.5 on 2026-02-12 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_mediopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elab', models.DateField(default=django.utils.timezone.now)),
                ('consecutivo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReciboCajaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('nit', models.CharField(blank=True, max_length=30, null=True)),
                ('factura_no', models.CharField(blank=True, max_length=30, null=True)),
                ('valor_factura', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pago', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('medio_pago_id', models.IntegerField(blank=True, null=True)),
                ('cuenta_contable', models.CharField(blank=True, max_length=30, null=True)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='myapp.recibocaja')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
