# Generated by Django 5.2.5 on 2026-02-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_recibocaja_recibocajalinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocaja',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.asientocontable'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='contabilizado',
            field=models.BooleanField(default=False),
        ),
    ]
