# Generated by Django 5.2.5 on 2026-02-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_recibocaja_asiento_recibocaja_contabilizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del concepto')),
                ('tipo', models.CharField(choices=[('devengos', 'Devengos'), ('deducciones', 'Deducciones'), ('carga', 'Carga prestacional'), ('pago', 'De pago')], max_length=20, verbose_name='Tipo de concepto')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
                'db_table': 'nomina_conceptos',
                'ordering': ['codigo'],
            },
        ),
    ]
