# Generated by Django 5.2.5 on 2026-02-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_conceptonomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('generales', 'Datos generales'), ('tipos_nomina', 'Tipos de Nómina'), ('tipos_contrato', 'Tipos de contrato'), ('areas', 'Áreas institucionales')], max_length=30)),
                ('consecutivo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nomina_parametros',
                'ordering': ['categoria', 'consecutivo'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'consecutivo'), name='uq_parametro_categoria_consecutivo')],
            },
        ),
    ]
