# Generated by Django 5.2.5 on 2026-02-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_parametronomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaParamConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc', models.CharField(blank=True, choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, null=True)),
                ('salarial', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True)),
                ('dc2', models.CharField(blank=True, choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametrizaciones', to='myapp.conceptonomina')),
                ('contracuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_param_contracuenta', to='myapp.cuentacontable')),
                ('contrato1', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato10', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato2', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato3', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato4', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato5', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato6', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato7', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato8', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('contrato9', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.parametronomina')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_param_cuenta', to='myapp.cuentacontable')),
                ('tipo_nomina', models.ForeignKey(limit_choices_to={'categoria': 'tipos_nomina'}, on_delete=django.db.models.deletion.CASCADE, related_name='param_conceptos_tipo_nomina', to='myapp.parametronomina')),
            ],
        ),
        migrations.CreateModel(
            name='NominaParamBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devengo', models.ForeignKey(limit_choices_to={'tipo': 'devengos'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='myapp.conceptonomina')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='myapp.nominaparamconcepto')),
            ],
        ),
        migrations.CreateModel(
            name='NominaParamTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='myapp.nominaparamconcepto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='nominaparamconcepto',
            index=models.Index(fields=['tipo_nomina'], name='myapp_nomin_tipo_no_e1afe8_idx'),
        ),
        migrations.AddIndex(
            model_name='nominaparamconcepto',
            index=models.Index(fields=['concepto'], name='myapp_nomin_concept_91ebfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='nominaparamconcepto',
            constraint=models.UniqueConstraint(fields=('tipo_nomina', 'concepto'), name='uniq_tipo_nomina_concepto'),
        ),
        migrations.AddConstraint(
            model_name='nominaparambase',
            constraint=models.UniqueConstraint(fields=('param', 'devengo'), name='uniq_param_devengo_base'),
        ),
        migrations.AddIndex(
            model_name='nominaparamtarifa',
            index=models.Index(fields=['param'], name='myapp_nomin_param_i_b9dfda_idx'),
        ),
    ]
