# Generated by Django 5.2.5 on 2026-02-24 18:20

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_nominaparamconcepto_nominaparambase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('nombre_1', models.CharField(blank=True, max_length=80)),
                ('nombre_2', models.CharField(blank=True, max_length=80)),
                ('apellido_1', models.CharField(blank=True, max_length=80)),
                ('apellido_2', models.CharField(blank=True, max_length=80)),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('no_contrato', models.CharField(blank=True, max_length=40)),
                ('fecha_terminacion_contrato', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo_personal', models.EmailField(blank=True, max_length=120)),
                ('correo_institucional', models.EmailField(blank=True, max_length=120)),
                ('telefono_1', models.CharField(blank=True, max_length=30)),
                ('telefono_2', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=180)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('sede', models.CharField(blank=True, max_length=80)),
                ('oficina', models.CharField(blank=True, max_length=80)),
                ('jefe_inmediato', models.CharField(blank=True, max_length=120)),
                ('banco_entidad', models.CharField(blank=True, max_length=120)),
                ('banco_tipo_cuenta', models.CharField(blank=True, choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro'), ('otro', 'Otro')], max_length=20)),
                ('banco_numero_cuenta', models.CharField(blank=True, max_length=40)),
                ('emergencia_nombre', models.CharField(blank=True, max_length=120)),
                ('emergencia_telefono', models.CharField(blank=True, max_length=30)),
                ('familia_padre', models.CharField(blank=True, max_length=120)),
                ('familia_madre', models.CharField(blank=True, max_length=120)),
                ('salud_entidad', models.CharField(blank=True, max_length=120)),
                ('salud_codigo', models.CharField(blank=True, max_length=40)),
                ('salud_nit', models.CharField(blank=True, max_length=40)),
                ('pension_entidad', models.CharField(blank=True, max_length=120)),
                ('pension_codigo', models.CharField(blank=True, max_length=40)),
                ('pension_nit', models.CharField(blank=True, max_length=40)),
                ('cesantias_entidad', models.CharField(blank=True, max_length=120)),
                ('cesantias_codigo', models.CharField(blank=True, max_length=40)),
                ('cesantias_nit', models.CharField(blank=True, max_length=40)),
                ('arl_riesgo', models.CharField(blank=True, choices=[('0.522', '0.522%'), ('1.44', '1.44%'), ('2.6', '2.6%'), ('4.55', '4.55%')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'categoria': 'areas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_area', to='myapp.parametronomina')),
                ('tipo_contrato', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'categoria': 'tipos_contrato'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_tipo_contrato', to='myapp.parametronomina')),
                ('tipo_nomina', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'categoria': 'tipos_nomina'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_tipo_nomina', to='myapp.parametronomina')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('certificado_bancario', 'Certificado bancario'), ('antecedentes_policia', 'Antecedentes Policía'), ('antecedentes_procuraduria', 'Antecedentes Procuraduría'), ('antecedentes_contraloria', 'Antecedentes Contraloría')], max_length=40)),
                ('archivo', models.FileField(upload_to=myapp.models.empleado_upload_path)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='myapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoEducacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=150)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='myapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='myapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoHijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='myapp.empleado')),
            ],
        ),
    ]
