# Generated by Django 5.2.5 on 2026-02-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_empleado_empleadoarchivo_empleadoeducacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=250)),
                ('contrato', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuenta_sueldo', models.BooleanField(default=False)),
                ('dias', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='myapp.conceptonomina')),
            ],
            options={
                'db_table': 'nomina_novedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
