# Generated by Django 5.2.5 on 2026-02-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_novedadnomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametronomina',
            name='categoria',
            field=models.CharField(choices=[('generales', 'Datos generales'), ('tipos_nomina', 'Tipos de Nómina'), ('tipos_contrato', 'Tipos de contrato'), ('areas', 'Áreas institucionales'), ('salario_minimo', 'Salario mínimo'), ('auxilio_transporte', 'Auxilio de transporte'), ('uvt', 'UVT')], max_length=30),
        ),
    ]
