# Generated by Django 5.2.5 on 2026-03-04 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_parametronomina_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(blank=True, default='', max_length=20, unique=True)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NominaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, default='', max_length=50)),
                ('cedula', models.CharField(db_index=True, max_length=30)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('cargo', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_nomina', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_contrato', models.CharField(blank=True, default='', max_length=255)),
                ('area', models.CharField(blank=True, default='', max_length=255)),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dias_laborados', models.IntegerField(default=0)),
                ('total_salario', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='myapp.nomina')),
            ],
        ),
        migrations.CreateModel(
            name='NominaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.conceptonomina')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='myapp.nomina')),
                ('nomina_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='myapp.nominaempleado')),
            ],
            options={
                'indexes': [models.Index(fields=['nomina', 'nomina_empleado'], name='myapp_nomin_nomina__07df6b_idx'), models.Index(fields=['nomina', 'concepto'], name='myapp_nomin_nomina__e1a02d_idx')],
            },
        ),
    ]
