# Generated by Django 5.2.5 on 2026-03-10 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_nomina_nominaempleado_nominamovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo_nomina', models.CharField(db_index=True, max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, default='', max_length=50)),
                ('cedula', models.CharField(db_index=True, max_length=30)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_nomina', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_contrato', models.CharField(blank=True, default='', max_length=255)),
                ('cargo', models.CharField(blank=True, default='', max_length=255)),
                ('area', models.CharField(blank=True, default='', max_length=255)),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pago', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('medio_pago', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_nomina', to='myapp.nomina')),
                ('nomina_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_nomina', to='myapp.nominaempleado')),
            ],
            options={
                'db_table': 'myapp_nominapago',
                'constraints': [models.UniqueConstraint(fields=('nomina', 'nomina_empleado'), name='uq_nominapago_nomina_empleado')],
            },
        ),
    ]
