# Generated by Django 5.2.5 on 2026-03-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_nominapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroDesprendibleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, default='', max_length=200)),
                ('nit', models.CharField(blank=True, default='', max_length=50)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('correo_electronico', models.CharField(blank=True, default='', max_length=150)),
                ('direccion', models.CharField(blank=True, default='', max_length=250)),
                ('pagina_web', models.CharField(blank=True, default='', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_desprendibles/')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro de desprendible de nómina',
                'verbose_name_plural': 'Parámetros de desprendibles de nómina',
            },
        ),
    ]
