# Generated by Django 5.2.5 on 2026-03-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_parametrodesprendiblenomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa_contable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, default='', max_length=200)),
                ('nit', models.CharField(blank=True, default='', max_length=50)),
                ('tel1', models.CharField(blank=True, default='', max_length=50)),
                ('tel2', models.CharField(blank=True, default='', max_length=50)),
                ('direccion', models.CharField(blank=True, default='', max_length=250)),
                ('sitio_web', models.CharField(blank=True, default='', max_length=250)),
                ('correo_notificaciones', models.EmailField(blank=True, default='', max_length=254)),
                ('regimen_tributario', models.CharField(blank=True, default='', max_length=100)),
                ('regimen_ica', models.CharField(blank=True, default='', max_length=100)),
                ('camara_comercio', models.CharField(blank=True, default='', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_contabilidad/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'empresa contable',
                'verbose_name_plural': 'empresa contable',
            },
        ),
        migrations.CreateModel(
            name='sucursal_contable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=50)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='myapp.empresa_contable')),
            ],
            options={
                'verbose_name': 'sucursal contable',
                'verbose_name_plural': 'sucursales contables',
                'ordering': ['id'],
            },
        ),
    ]
