# Generated by Django 5.2.5 on 2026-03-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_empresa_contable_sucursal_contable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('contabilidad', 'Contabilidad'), ('facturacion', 'Facturación'), ('recibos_caja', 'Recibos de caja'), ('nomina', 'Nómina'), ('pagos_nomina', 'Pagos de nómina'), ('gestion_compras', 'Gestión de compras')], max_length=50, unique=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_1', models.DateField(blank=True, null=True)),
                ('fecha_fin_2', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bloqueo contable',
                'verbose_name_plural': 'Bloqueos contables',
                'db_table': 'bloqueos_contables',
                'ordering': ['id'],
            },
        ),
    ]
